### ISSUE TITLE
Freemium, without details

### ISSUE THREAD

**Issue by antonmarin** [Chieze-Franklin/githint-bot#25]
Open https://github.com/marketplace/githint-bot.
It's freemium. Where i can find conditions?

Click "install it for free".
We see that it's 0$ for year. What will be next?

Open https://githint.herokuapp.com/.
No info about pricing too.

Why it's freemium and what are conditions of using it free?

**Comment by Chieze-Franklin** [comment]
Hi @antonmarin 

Thanks for reaching out. I started this as a side project to solve issues I was having with the teams I was managing. I have absolutely no intention of ever monetizing this tool.

As for necessary info, what is required of me (by GitHub) is to provide:

1. A support link: https://githint.herokuapp.com/support
2. A link to the privacy policy: https://githint.herokuapp.com/privacy

I will try my best to invest more time on the tool (and documentation) come January.

Feel free to reach out with more questions.

Cheers!

**Comment by antonmarin** [comment]
Thanks a lot 🔥
