### ISSUE TITLE
check for .githint.json file fails with 404

### ISSUE THREAD

**Issue by lior-neuman** [Chieze-Franklin/githint-bot#29]
Githint seems to be unable to read the .githint.json file, even though it exists at the root of the repository.

I'm guessing here, but it was installed in a private repository, and during installation no access to the code was requested.

**Comment by Chieze-Franklin** [comment]
Hi @lior-neuman 

Thanks for the feedback. The bot hasn't been tested with private repos. I don't expect it to work well with them.

I will try my best to find time this year to address that.

Cheers.
